doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        types:
            !php/const App\Doctrine\Type\PixelSizeType::NAME: App\Doctrine\Type\PixelSizeType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping'
                prefix: 'App\Entity'
                alias: App
