name: Backend build

on:
    workflow_dispatch: ~ # Allow for manual dispatching
    push: ~
    pull_request: ~
    schedule:
        -
            cron: "0 1 * * 6" # Run at 1am every Saturday

defaults:
    run:
        working-directory: backend

jobs:
    build:
        name: "PHP ${{ matrix.php }}"
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                php: [8.0]

        services:
            postgres:
                image: postgres:13
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: meme
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none

            -   name: Install dependencies
                run: composer install

            -   name: Run analysis
                run: composer analyse

            -   name: Setup database
                run: bin/console doctrine:schema:create

            -   name: Run tests
                run: composer test
